const Map<String, String> appLocalizationsDe = {
  'financeTracker': 'Finanz-Tracker',
  'addTransaction': 'Transaktion hinzufügen',
  'addTransactionTitle': 'Transaktion hinzufügen',
  'editTransactionTitle': 'Transaktion bearbeiten',
  'save': 'Speichern',
  'delete': 'Löschen',
  'deleteTransactionTitle': 'Transaktion löschen?',
  'deleteTransactionBody': 'Diese Aktion kann nicht rückgängig gemacht werden.',
  'cancel': 'Abbrechen',
  'toggleTheme': 'Design umschalten',
  'toggleLanguage': 'Sprache wechseln',
  'demo': 'Demo',
  'spendingByCategory': 'Ausgaben nach Kategorie',
  'transactions': 'Transaktionen',
  'currentBalance': 'Aktueller Kontostand',
  'noTransactionsYet': 'Noch keine Transaktionen',
  'addFirstTransaction': 'Füge deine erste Einnahme oder Ausgabe hinzu.',
  'retry': 'Erneut versuchen',
  'somethingWentWrong': 'Etwas ist schiefgelaufen.',
  'noExpensesYet': 'Noch keine Ausgaben.',
  'showMore': 'Mehr anzeigen',
  'showLess': 'Weniger anzeigen',
  'chartHint':
      'Balken zeigen jede Kategorie als Anteil der Gesamtausgaben im gewählten Zeitraum.',
  'allDates': 'Alle Daten',
  'expenses': 'Ausgaben',
  'income': 'Einnahmen',
  'selectDate': 'Datum auswählen',
  'selectDateRange': 'Datumsbereich auswählen',
  'clear': 'Zurücksetzen',
  'lastMonth': 'Letzter Monat',
  'lastQuarter': 'Letztes Quartal',
  'lastYear': 'Letztes Jahr',
  'start': 'Start',
  'end': 'Ende',
  'showActivities': 'Aktivitäten anzeigen',
  'selectCategory': 'Kategorie auswählen',
  'searchCategories': 'Kategorien suchen',
  'noMatchesFound': 'Keine Treffer gefunden.',
  'amount': 'Betrag',
  'category': 'Kategorie',
  'date': 'Datum',
  'notesOptional': 'Notizen (optional)',
  'expense': 'Ausgabe',
  'enterValidAmount': 'Bitte einen gültigen Betrag eingeben.',
  'amountRequired': 'Betrag ist erforderlich.',
  'categoryRequired': 'Kategorie ist erforderlich.',
};
