const Map<String, String> appLocalizationsEn = {
  'financeTracker': 'Finance Tracker',
  'addTransaction': 'Add transaction',
  'addTransactionTitle': 'Add Transaction',
  'editTransactionTitle': 'Edit Transaction',
  'save': 'Save',
  'delete': 'Delete',
  'deleteTransactionTitle': 'Delete transaction?',
  'deleteTransactionBody': 'This action cannot be undone.',
  'cancel': 'Cancel',
  'toggleTheme': 'Toggle theme',
  'toggleLanguage': 'Switch language',
  'demo': 'Demo',
  'spendingByCategory': 'Spending by category',
  'transactions': 'Transactions',
  'currentBalance': 'Current balance',
  'noTransactionsYet': 'No transactions yet',
  'addFirstTransaction': 'Add your first income or expense.',
  'retry': 'Retry',
  'somethingWentWrong': 'Something went wrong.',
  'noExpensesYet': 'No expenses yet.',
  'showMore': 'Show more',
  'showLess': 'Show less',
  'chartHint':
      'Bars show each category as a share of total expenses for the selected date range.',
  'allDates': 'All dates',
  'expenses': 'Expenses',
  'income': 'Income',
  'selectDate': 'Select a date',
  'selectDateRange': 'Select a date range',
  'clear': 'Clear',
  'lastMonth': 'Last month',
  'lastQuarter': 'Last quarter',
  'lastYear': 'Last year',
  'start': 'Start',
  'end': 'End',
  'showActivities': 'Show activities',
  'selectCategory': 'Select a category',
  'searchCategories': 'Search categories',
  'noMatchesFound': 'No matches found.',
  'amount': 'Amount',
  'category': 'Category',
  'date': 'Date',
  'notesOptional': 'Notes (optional)',
  'expense': 'Expense',
  'enterValidAmount': 'Enter a valid amount.',
  'amountRequired': 'Amount is required.',
  'categoryRequired': 'Category is required.',
};
